import { Translations } from './types';

export const en: Translations = {
  auth: {
    login: {
      title: 'Login',
      email: 'Email',
      password: 'Password',
      loginButton: 'Login',
      forgotPassword: 'Forgot password,',
      resetPassword: 'Reset password',
      activateAccount: 'To activate your account,',
      activate: 'Activate',
      loginError: 'Login failed',
      checkCredentials: 'Please check your credentials.',
      authError: 'Authorization Error',
      roleNotDefined: 'Your role is not defined.',
    },
    forgotPassword: {
      title: 'Password Reset',
      email: 'Email',
      emailPlaceholder: 'Enter your email address',
      sendButton: 'Send Reset Link',
      sendResetLink: 'Send Reset Link',
      backToLogin: 'Back to Login',
      resetLinkSent: 'Reset Link Sent',
      checkEmail: 'Please check your email.',
      error: 'Error',
      tryAgain: 'Please try again.',
    },
    activation: {
      title: 'Account Activation',
      emailPlaceholder: 'Enter your email address',
      sendButton: 'Send Activation Email',
      orText: 'or',
      tokenPlaceholder: 'Enter activation code',
      activationCode: 'Activation Code',
      activateButton: 'Activate',
      backToLogin: 'Back to Login',
      activationSuccess: 'Activation Successful',
      accountActivated: 'Your account has been successfully activated.',
      activationError: 'Activation Error',
      invalidCode: 'Invalid activation code.',
    },
  },
  userDashboard: {
    loading: 'Loading dashboard...',
    welcome: 'Welcome!',
    myInfo: 'My Information',
    department: 'Department',
    company: 'Company',
    joinDate: 'Join Date',
    email: 'Email'
  },
  userProfile: {
    loading: 'Loading profile...',
    title: 'Profile Information',
    generalInfo: 'General Information',
    personalInfo: 'Personal Information',
    changePassword: 'Change Password',
    department: 'Department',
    company: 'Company',
    role: 'Role',
    joinDate: 'Join Date',
    name: 'Name',
    surname: 'Surname',
    email: 'Email',
    phone: 'Phone',
    currentPassword: 'Current Password',
    newPassword: 'New Password (At least 6 characters)',
    confirmPassword: 'Confirm New Password',
    changePasswordButton: 'Change Password',
    unassigned: 'Unassigned',
    unknown: 'Unknown'
  },
  userCompanyInfo: {
    loading: 'Loading company information...',
    error: 'An error occurred while loading company information.',
    retry: 'Retry',
    companyInfo: 'Company Information',
    departmentInfo: 'Department Information',
    noCompanyTitle: 'Company Information Not Found',
    noCompanyText: 'You are not yet associated with a company. Please contact your administrator for company assignment.',
    noDepartmentTitle: 'Department Information Not Found',
    noDepartmentText: 'You have not been assigned to a department yet. Please contact your administrator for department assignment.',
    active: 'Active',
    departmentName: 'Department Name',
    userRole: 'User Role',
    joinDate: 'Join Date',
    notSpecified: 'Not Specified',
    companyName: 'Company Name',
    companyCode: 'Company Code',
    companyAddress: 'Company Address',
    companyPhone: 'Company Phone',
    companyEmail: 'Company Email',
    companyWebsite: 'Company Website',
    establishedDate: 'Established Date',
    employeeCount: 'Employee Count'
  },
  managerDashboard: {
    loading: 'Loading dashboard...',
    welcome: 'Welcome!',
    departmentStats: 'Department Statistics',
    totalEmployees: 'Total Employees',
    managedDepartments: 'Managed Departments',
    quickActions: 'Quick Actions',
    departmentEmployees: 'Department Employees',
    profileSettings: 'Profile Settings',
    department: 'Department'
  },
  managerProfile: {
    loading: 'Loading profile...',
    title: 'Profile Information',
    generalInfo: 'General Information',
    personalInfo: 'Personal Information',
    changePassword: 'Change Password',
    department: 'Department',
    role: 'Role',
    name: 'Name',
    surname: 'Surname',
    email: 'Email',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    changePasswordButton: 'Change Password',
    passwordMismatch: 'New passwords do not match',
    passwordChangeSuccess: 'Password successfully updated',
    passwordChangeError: 'Password change failed',
    profileLoadError: 'Could not load profile information'
  },
  managerUserList: {
    loading: 'Loading users...',
    department: 'Department',
    role: 'Role',
    deleteUser: 'Delete User',
    deleteConfirmation: 'Are you sure you want to delete this user?',
    cancel: 'Cancel',
    delete: 'Delete',
    deleteSuccess: 'User successfully deleted.',
    deleteError: 'An error occurred while deleting the user.',
    emptyList: 'No users found in this department yet.',
    usersLoadError: 'Could not load users'
  },
  common: {
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    refresh: 'Refresh',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    close: 'Close',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    logout: 'Logout',
  },
};