import { Translations } from './types';

export const en: Translations = {
  auth: {
    login: {
      title: 'Login',
      email: 'Email',
      password: 'Password',
      loginButton: 'Login',
      forgotPassword: 'Forgot password,',
      resetPassword: 'Reset password',
      activateAccount: 'To activate your account,',
      activate: 'Activate',
      loginError: 'Login failed',
      checkCredentials: 'Please check your credentials.',
      authError: 'Authorization Error',
      roleNotDefined: 'Your role is not defined.',
    },
    forgotPassword: {
      title: 'Password Reset',
      email: 'Email',
      emailPlaceholder: 'Enter your email address',
      sendButton: 'Send Reset Link',
      sendResetLink: 'Send Reset Link',
      backToLogin: 'Back to Login',
      resetLinkSent: 'Reset Link Sent',
      checkEmail: 'Please check your email.',
      error: 'Error',
      tryAgain: 'Please try again.',
    },
    activation: {
      title: 'Account Activation',
      emailPlaceholder: 'Enter your email address',
      sendButton: 'Send Activation Email',
      orText: 'or',
      tokenPlaceholder: 'Enter activation code',
      activationCode: 'Activation Code',
      activateButton: 'Activate',
      backToLogin: 'Back to Login',
      activationSuccess: 'Activation Successful',
      accountActivated: 'Your account has been successfully activated.',
      activationError: 'Activation Error',
      invalidCode: 'Invalid activation code.',
      newPasswordPlaceholder: 'Enter new password',
      confirmPasswordPlaceholder: 'Confirm new password',
    },
  },
  userDashboard: {
    loading: 'Loading dashboard...',
    welcome: 'Welcome!',
    myInfo: 'My Information',
    department: 'Department',
    company: 'Company',
    joinDate: 'Join Date',
    email: 'Email',
    unassigned: 'Unassigned',
    unknown: 'Unknown',
    error: 'Error',
    dataLoadError: 'Failed to load dashboard data',
    dashboardDataError: 'An error occurred while loading dashboard data'
  },
  userProfile: {
    loading: 'Loading profile...',
    title: 'Profile Information',
    generalInfo: 'General Information',
    personalInfo: 'Personal Information',
    changePassword: 'Change Password',
    department: 'Department',
    company: 'Company',
    role: 'Role',
    joinDate: 'Join Date',
    name: 'Name',
    surname: 'Surname',
    email: 'Email',
    phone: 'Phone',
    currentPassword: 'Current Password',
    newPassword: 'New Password (At least 6 characters)',
    confirmPassword: 'Confirm New Password',
    changePasswordButton: 'Change Password',
    unassigned: 'Unassigned',
    unknown: 'Unknown',
    logoutTitle: 'Logout',
    logoutMessage: 'Are you sure you want to logout?',
    cancel: 'Cancel',
    logout: 'Logout',
    error: 'Error',
    profileLoadError: 'Failed to load profile information',
    fillAllFields: 'Please fill all fields',
    passwordMismatch: 'New passwords do not match',
    passwordMinLength: 'New password must be at least 6 characters',
    success: 'Success',
    passwordChangeSuccess: 'Password updated successfully',
    passwordChangeError: 'Password change failed. Please check your current password.'
  },
  userCompanyInfo: {
    loading: 'Loading company information...',
    error: 'An error occurred while loading company information.',
    retry: 'Retry',
    companyInfo: 'Company Information',
    departmentInfo: 'Department Information',
    noCompanyTitle: 'Company Information Not Found',
    noCompanyText: 'You are not yet associated with a company. Please contact your administrator for company assignment.',
    noDepartmentTitle: 'Department Information Not Found',
    noDepartmentText: 'You have not been assigned to a department yet. Please contact your administrator for department assignment.',
    active: 'Active',
    departmentName: 'Department Name',
    userRole: 'User Role',
    joinDate: 'Join Date',
    notSpecified: 'Not Specified',
    companyName: 'Company Name',
    companyCode: 'Company Code',
    companyAddress: 'Company Address',
    companyPhone: 'Company Phone',
    companyEmail: 'Company Email',
    companyWebsite: 'Company Website',
    establishedDate: 'Established Date',
    employeeCount: 'Employee Count',
    companyType: 'Company Type',
    user: 'User',
    email: 'Email',
    role: 'Role',
    name: 'Name',
    surname: 'Surname',
    emailNotSpecified: 'Email not specified',
    roleNotSpecified: 'Role not specified',
    addressNotSpecified: 'Address not specified',
    inactive: 'Inactive',
    defaultRole: 'USER'
  },
  managerDashboard: {
    loading: 'Loading dashboard...',
    welcome: 'Welcome!',
    departmentStats: 'Department Statistics',
    totalEmployees: 'Total Employees',
    managedDepartments: 'Managed Departments',
    quickActions: 'Quick Actions',
    departmentEmployees: 'Department Employees',
    companies: 'Companies',
    profileSettings: 'Profile Settings',
    department: 'Department',
    unknown: 'Unknown',
    dataLoadError: 'Failed to load dashboard data:',
    error: 'Error',
    dashboardDataError: 'An error occurred while loading dashboard data'
  },
  managerProfile: {
    loading: 'Loading profile...',
    title: 'Profile Information',
    generalInfo: 'General Information',
    personalInfo: 'Personal Information',
    changePassword: 'Change Password',
    department: 'Department',
    role: 'Role',
    name: 'Name',
    surname: 'Surname',
    email: 'Email',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    changePasswordButton: 'Change Password',
    passwordMismatch: 'New passwords do not match',
    passwordChangeSuccess: 'Password updated successfully',
    passwordChangeError: 'Password change failed',
    profileLoadError: 'Failed to load profile information'
  },
  managerUserList: {
    loading: 'Loading users...',
    department: 'Department',
    role: 'Role',
    deleteUser: 'Delete User',
    deleteConfirmation: 'Are you sure you want to delete this user?',
    cancel: 'Cancel',
    delete: 'Delete',
    deleteSuccess: 'User deleted successfully.',
    deleteError: 'An error occurred while deleting the user.',
    emptyList: 'No users found in this department.',
    usersLoadError: 'Failed to load users'
  },
  managerCompanyList: {
    loading: 'Loading company...',
    title: 'Company Information',
    companiesCount: 'companies',
    active: 'Active',
    inactive: 'Inactive',
    companyType: 'Type',
    district: 'District',
    city: 'City',
    region: 'Region',
    address: 'Address',
    createdDate: 'Created',
    viewDetails: 'View Details',
    companiesLoadError: 'Error loading company information'
  },
  adminDashboard: {
    loading: 'Loading dashboard...',
    welcome: 'Welcome!',
    systemStats: 'System Statistics',
    totalUsers: 'Total Users',
    totalCompanies: 'Total Companies',
    totalDepartments: 'Total Departments',
    activeUsers: 'Active Users',
    pendingUsers: 'Pending Users',
    dataLoadError: 'An error occurred while loading dashboard data',
    management: 'Management',
    departmentTypes: 'Department Types'
  },
  bottomTabs: {
    admin: 'Admin',
    companies: 'Companies',
    users: 'Users',
    home: 'Home',
    profile: 'Profile',
    companyInfo: 'Company Info'
  },
  adminUserList: {
    loading: 'Loading...',
    addNewUser: 'Add New User',
    edit: 'Edit',
    delete: 'Delete',
    deleteUser: 'Delete User',
    deleteConfirmation: 'Are you sure you want to delete this user?',
    cancel: 'Cancel',
    deleteSuccess: 'User deleted',
    deleteError: 'User could not be deleted',
    usersLoadError: 'Users could not be loaded',
    email: 'Email',
    role: 'Role',
    department: 'Department',
    company: 'Company',
  },
  adminUserForm: {
    loading: 'Loading...',
    name: 'Name',
    surname: 'Surname',
    email: 'Email',
    department: 'Department',
    role: 'Role',
    isActive: 'Active',
    isActiveLabel: 'Active Status',
    selectDepartment: 'Select Department',
    save: 'Save',
    warning: 'Warning',
    selectDepartmentWarning: 'Please select a department.',
    saveSuccess: 'User saved',
    saveError: 'User could not be saved',
    userLoadError: 'User information could not be loaded',
    departmentsLoadError: 'Departments could not be loaded'
  },
  companyList: {
    loading: 'Loading...',
    companiesLoadError: 'Companies could not be loaded',
    deleteSuccess: 'Company deleted',
    deleteError: 'Company could not be deleted',
    addNewCompany: 'Add New Company',
    detail: 'Detail',
    edit: 'Edit',
    delete: 'Delete',
    district: 'District',
    city: 'City',
    region: 'Region',
    address: 'Address',
    notSpecified: 'Not specified'
  },
  companyForm: {
    loading: 'Loading...',
    companyName: 'Company Name',
    shortName: 'Short Name',
    addressDetail: 'Address Detail',
    region: 'Region',
    city: 'City',
    district: 'District',
    selectRegion: 'Please select region',
    selectCity: 'Please select city',
    selectDistrict: 'Please select district',
    active: 'Active?',
    companyInfoError: 'Company information could not be loaded',
    regionsError: 'Regions could not be loaded',
    citiesError: 'Cities could not be loaded',
    allCitiesError: 'All cities could not be loaded either',
    districtsError: 'Districts could not be loaded',
    allDistrictsError: 'All districts could not be loaded either',
    districtDetailsError: 'District details could not be loaded',
    updateSuccess: 'Company updated',
    updateError: 'Company could not be updated'
  },
  createCompany: {
    title: 'Create New Company',
    companyName: 'Company Name',
    shortName: 'Short Name',
    addressDetail: 'Address Detail',
    district: 'District',
    selectDistrict: 'Please select district',
    companyType: 'Company Type',
    selectCompanyType: 'Please select company type',
    active: 'Active?',
    create: 'Create',
    missingInfo: 'Missing Information',
    enterCompanyNameAndShort: 'Please enter company name and short name.',
    createSuccess: 'New company created',
    createError: 'Company could not be created',
    districtsLoadError: 'Districts could not be loaded',
    companyTypesLoadError: 'Company types could not be loaded'
  },
  companyDetail: {
    title: '🏢 Company Detail Page',
    departments: 'Departments'
  },
  departmentList: {
    title: 'Departments',
    addDepartment: '+ Add Department',
    detail: 'Detail',
    edit: 'Edit',
    delete: 'Delete',
    departmentsLoadError: 'Departments could not be loaded',
    districtsLoadError: 'Districts could not be loaded',
    departmentName: 'Department Name',
    departmentNamePlaceholder: 'Enter department name',
    selectDistrict: 'Select District',
    selectDistrictPlaceholder: 'Select district...',
    addressDetail: 'Address Detail',
    addressDetailPlaceholder: 'Enter address detail',
    newDepartment: 'Add New Department',
    editDepartment: 'Edit Department',
    nameRequired: 'Department name cannot be empty',
    addressRequired: 'Address detail cannot be empty',
    addSuccess: 'Department added successfully',
    addError: 'Department could not be added',
    updateSuccess: 'Department updated successfully',
    updateError: 'Department could not be updated',
    deleteError: 'Could not be deleted'
  },
  departmentDetail: {
    loading: 'Loading department information...',
    departmentDetailsError: 'Department details could not be loaded',
    departmentUsersError: 'Department users could not be loaded',
    notFound: 'Department not found',
    departmentInfo: 'Department Information',
    departmentType: 'Department Type:',
    cityRegion: 'City/Region:',
    district: 'District:',
    address: 'Address:',
    departmentManager: 'Department Manager',
    noManager: 'No manager assigned to this department yet',
    departmentEmployees: 'Department Employees',
    noEmployees: 'No employees in this department yet'
  },
  departmentTypeList: {
    title: 'Department Type Management',
    loading: 'Loading department types...',
    addNewDepartmentType: 'Add New Department Type',
    edit: 'Edit',
    delete: 'Delete',
    deleteDepartmentType: 'Delete Department Type',
    deleteConfirmation: 'Are you sure you want to delete this department type?',
    cancel: 'Cancel',
    deleteSuccess: 'Department type deleted successfully',
    deleteError: 'An error occurred while deleting the department type',
    departmentTypesLoadError: 'An error occurred while loading department types',
    emptyList: 'No department types found yet',
    departmentTypeName: 'Department Type Name',
    active: 'Active',
    inactive: 'Inactive',
    status: 'Status'
  },
  departmentTypeForm: {
    title: 'New Department Type',
    editTitle: 'Edit Department Type',
    departmentTypeName: 'Department Type Name',
    departmentTypeNamePlaceholder: 'Enter department type name',
    isActive: 'Active',
    isActiveLabel: 'Active Status',
    save: 'Save',
    loading: 'Loading...',
    saveSuccess: 'Department type saved successfully',
    saveError: 'An error occurred while saving the department type',
    departmentTypeLoadError: 'An error occurred while loading department type information',
    nameRequired: 'Department type name is required'
  },
  companyTypeList: {
    title: 'Company Type Management',
    loading: 'Loading company types...',
    addNewCompanyType: 'Add New Company Type',
    edit: 'Edit',
    delete: 'Delete',
    deleteCompanyType: 'Delete Company Type',
    deleteConfirmation: 'Are you sure you want to delete this company type?',
    cancel: 'Cancel',
    deleteSuccess: 'Company type deleted successfully',
    deleteError: 'An error occurred while deleting the company type',
    companyTypesLoadError: 'An error occurred while loading company types',
    emptyList: 'No company types found yet',
    companyTypeName: 'Company Type Name',
    active: 'Active',
    inactive: 'Inactive',
    status: 'Status'
  },
  companyTypeForm: {
    title: 'New Company Type',
    editTitle: 'Edit Company Type',
    companyTypeName: 'Company Type Name',
    companyTypeNamePlaceholder: 'Enter company type name',
    isActive: 'Active',
    isActiveLabel: 'Active Status',
    save: 'Save',
    loading: 'Loading...',
    saveSuccess: 'Company type saved successfully',
    saveError: 'An error occurred while saving the company type',
    companyTypeLoadError: 'An error occurred while loading company type information',
    nameRequired: 'Company type name is required'
  },
  locationManagement: {
    regionList: {
      title: 'Region Management',
      loading: 'Loading regions...',
      addNewRegion: 'Add New Region',
      edit: 'Edit',
      delete: 'Delete',
      deleteRegion: 'Delete Region',
      deleteConfirmation: 'Are you sure you want to delete this region?',
      cancel: 'Cancel',
      deleteSuccess: 'Region deleted successfully',
      deleteError: 'An error occurred while deleting the region',
      regionsLoadError: 'An error occurred while loading regions',
      emptyList: 'No regions found yet',
      regionName: 'Region Name'
    },
    regionForm: {
      title: 'New Region',
      editTitle: 'Edit Region',
      regionName: 'Region Name',
      regionNamePlaceholder: 'Enter region name',
      save: 'Save',
      loading: 'Loading...',
      saveSuccess: 'Region saved successfully',
      saveError: 'An error occurred while saving the region',
      regionLoadError: 'An error occurred while loading region information',
      nameRequired: 'Region name is required'
    },
    cityList: {
      title: 'City Management',
      loading: 'Loading cities...',
      addNewCity: 'Add New City',
      edit: 'Edit',
      delete: 'Delete',
      deleteCity: 'Delete City',
      deleteConfirmation: 'Are you sure you want to delete this city?',
      cancel: 'Cancel',
      deleteSuccess: 'City deleted successfully',
      deleteError: 'An error occurred while deleting the city',
      citiesLoadError: 'An error occurred while loading cities',
      emptyList: 'No cities found yet',
      cityName: 'City Name',
      region: 'Region',
      deleteTitle: 'Delete Title'
    },
    cityForm: {
      title: 'New City',
      editTitle: 'Edit City',
      cityName: 'City Name',
      cityNamePlaceholder: 'Enter city name',
      region: 'Region',
      selectRegion: 'Select region',
      save: 'Save',
      loading: 'Loading...',
      saveSuccess: 'City saved successfully',
      saveError: 'An error occurred while saving the city',
      cityLoadError: 'An error occurred while loading city information',
      regionsLoadError: 'An error occurred while loading regions',
      nameRequired: 'City name is required',
      regionRequired: 'Region selection is required'
    },
    townList: {
      title: 'District Management',
      loading: 'Loading districts...',
      addNewTown: 'Add New District',
      edit: 'Edit',
      delete: 'Delete',
      deleteTown: 'Delete District',
      deleteTitle: 'Delete District',
      deleteConfirmation: 'Are you sure you want to delete this district?',
      cancel: 'Cancel',
      deleteSuccess: 'District deleted successfully',
      deleteError: 'An error occurred while deleting the district',
      townsLoadError: 'An error occurred while loading districts',
      emptyList: 'No districts found yet',
      townName: 'District Name',
      city: 'City',
      region: 'Region'
    },
    townForm: {
      title: 'New District',
      editTitle: 'Edit District',
      townName: 'District Name',
      townNamePlaceholder: 'Enter district name',
      region: 'Region',
      selectRegion: 'Select region',
      city: 'City',
      selectCity: 'Select city',
      save: 'Save',
      loading: 'Loading...',
      saveSuccess: 'District saved successfully',
      updateSuccess: 'District updated successfully',
      saveError: 'An error occurred while saving the district',
      townLoadError: 'An error occurred while loading district information',
      regionsLoadError: 'An error occurred while loading regions',
      citiesLoadError: 'An error occurred while loading cities',
      nameRequired: 'District name is required'
    }
  },
  common: {
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    update: 'Update',
    search: 'Search',
    filter: 'Filter',
    refresh: 'Refresh',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    close: 'Close',
    confirm: 'Confirm',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    logout: 'Logout',
    logoutError: 'An error occurred while logging out'
  },
};