import { Translations } from './types';

export const tr: Translations = {
  auth: {
    login: {
      title: 'Giriş Yap',
      email: 'E-Posta',
      password: 'Şifre',
      loginButton: 'Giriş',
      forgotPassword: 'Şifremi unuttum,',
      resetPassword: 'Şifre sıfırla',
      activateAccount: 'Hesabını aktive etmek için,',
      activate: 'Aktive et',
      loginError: 'Giriş başarısız',
      checkCredentials: 'Lütfen bilgilerinizi kontrol edin.',
      authError: 'Yetki Hatası',
      roleNotDefined: 'Yetkiniz tanımlı değil.',
    },
    forgotPassword: {
      title: 'Şifre Sıfırlama',
      email: 'E-Posta',
      emailPlaceholder: 'E-posta adresinizi girin',
      sendButton: 'Sıfırlama Bağlantısı Gönder',
      sendResetLink: 'Sıfırlama Bağlantısı Gönder',
      backToLogin: 'Giriş Sayfasına Dön',
      resetLinkSent: 'Sıfırlama Bağlantısı Gönderildi',
      checkEmail: 'E-posta adresinizi kontrol edin.',
      error: 'Hata',
      tryAgain: 'Lütfen tekrar deneyin.',
    },
    activation: {
      title: 'Hesap Aktivasyonu',
      emailPlaceholder: 'E-posta adresinizi girin',
      sendButton: 'Aktivasyon E-postası Gönder',
      orText: 'veya',
      tokenPlaceholder: 'Aktivasyon kodunu girin',
      activationCode: 'Aktivasyon Kodu',
      activateButton: 'Aktive Et',
      backToLogin: 'Giriş Sayfasına Dön',
      activationSuccess: 'Aktivasyon Başarılı',
      accountActivated: 'Hesabınız başarıyla aktive edildi.',
      activationError: 'Aktivasyon Hatası',
      invalidCode: 'Geçersiz aktivasyon kodu.',
    },
  },
  userDashboard: {
    loading: 'Dashboard yükleniyor...',
    welcome: 'Hoş Geldin!',
    myInfo: 'Bilgilerim',
    department: 'Departman',
    company: 'Şirket',
    joinDate: 'Katılım',
    email: 'E-posta'
  },
  userProfile: {
    loading: 'Profil yükleniyor...',
    title: 'Profil Bilgileri',
    generalInfo: 'Genel Bilgiler',
    personalInfo: 'Kişisel Bilgiler',
    changePassword: 'Şifre Değiştir',
    department: 'Departman',
    company: 'Şirket',
    role: 'Rol',
    joinDate: 'Katılım Tarihi',
    name: 'Ad',
    surname: 'Soyad',
    email: 'E-posta',
    phone: 'Telefon',
    currentPassword: 'Mevcut Şifre',
    newPassword: 'Yeni Şifre (En az 6 karakter)',
    confirmPassword: 'Yeni Şifre (Tekrar)',
    changePasswordButton: 'Şifre Değiştir',
    unassigned: 'Atanmamış',
    unknown: 'Bilinmiyor'
  },
  userCompanyInfo: {
    loading: 'Şirket bilgileri yükleniyor...',
    error: 'Şirket bilgileri yüklenirken bir hata oluştu.',
    retry: 'Tekrar Dene',
    companyInfo: 'Şirket Bilgileri',
    departmentInfo: 'Departman Bilgileri',
    noCompanyTitle: 'Şirket Bilgisi Bulunamadı',
    noCompanyText: 'Henüz bir şirkete bağlı değilsiniz. Şirket ataması için yöneticinizle iletişime geçin.',
    noDepartmentTitle: 'Departman Bilgisi Bulunamadı',
    noDepartmentText: 'Henüz bir departmana atanmadınız. Departman ataması için yöneticinizle iletişime geçin.',
    active: 'Aktif',
    departmentName: 'Departman Adı',
    userRole: 'Kullanıcı Rolü',
    joinDate: 'Katılım Tarihi',
    notSpecified: 'Belirtilmemiş',
    companyName: 'Şirket Adı',
    companyCode: 'Şirket Kodu',
    companyAddress: 'Şirket Adresi',
    companyPhone: 'Şirket Telefonu',
    companyEmail: 'Şirket E-postası',
    companyWebsite: 'Şirket Web Sitesi',
    establishedDate: 'Kuruluş Tarihi',
    employeeCount: 'Çalışan Sayısı'
  },
  common: {
    loading: 'Yükleniyor...',
    error: 'Hata',
    success: 'Başarılı',
    cancel: 'İptal',
    save: 'Kaydet',
    delete: 'Sil',
    edit: 'Düzenle',
    add: 'Ekle',
    search: 'Ara',
    filter: 'Filtrele',
    refresh: 'Yenile',
    back: 'Geri',
    next: 'İleri',
    previous: 'Önceki',
    close: 'Kapat',
    confirm: 'Onayla',
    yes: 'Evet',
    no: 'Hayır',
  },
};