import { Translations } from './types';

export const tr: Translations = {
  auth: {
    login: {
      title: 'Giriş Yap',
      email: 'E-Posta',
      password: 'Şifre',
      loginButton: 'Giriş',
      forgotPassword: 'Şifremi unuttum,',
      resetPassword: 'Şifre sıfırla',
      activateAccount: 'Hesabını aktive etmek için,',
      activate: 'Aktive et',
      loginError: 'Giriş başarısız',
      checkCredentials: 'Lütfen bilgilerinizi kontrol edin.',
      authError: 'Yetki Hatası',
      roleNotDefined: 'Yetkiniz tanımlı değil.',
    },
    forgotPassword: {
      title: 'Şifre Sıfırlama',
      email: 'E-Posta',
      emailPlaceholder: 'E-posta adresinizi girin',
      sendButton: 'Sıfırlama Bağlantısı Gönder',
      sendResetLink: 'Sıfırlama Bağlantısı Gönder',
      backToLogin: 'Giriş Sayfasına Dön',
      resetLinkSent: 'Sıfırlama Bağlantısı Gönderildi',
      checkEmail: 'E-posta adresinizi kontrol edin.',
      error: 'Hata',
      tryAgain: 'Lütfen tekrar deneyin.',
    },
    activation: {
      title: 'Hesap Aktivasyonu',
      emailPlaceholder: 'E-posta adresinizi girin',
      sendButton: 'Aktivasyon E-postası Gönder',
      orText: 'veya',
      tokenPlaceholder: 'Aktivasyon kodunu girin',
      activationCode: 'Aktivasyon Kodu',
      activateButton: 'Aktive Et',
      backToLogin: 'Giriş Sayfasına Dön',
      activationSuccess: 'Aktivasyon Başarılı',
      accountActivated: 'Hesabınız başarıyla aktive edildi.',
      activationError: 'Aktivasyon Hatası',
      invalidCode: 'Geçersiz aktivasyon kodu.',
    },
  },
  userDashboard: {
    loading: 'Dashboard yükleniyor...',
    welcome: 'Hoş Geldin!',
    myInfo: 'Bilgilerim',
    department: 'Departman',
    company: 'Şirket',
    joinDate: 'Katılım',
    email: 'E-posta'
  },
  userProfile: {
    loading: 'Profil yükleniyor...',
    title: 'Profil Bilgileri',
    generalInfo: 'Genel Bilgiler',
    personalInfo: 'Kişisel Bilgiler',
    changePassword: 'Şifre Değiştir',
    department: 'Departman',
    company: 'Şirket',
    role: 'Rol',
    joinDate: 'Katılım Tarihi',
    name: 'Ad',
    surname: 'Soyad',
    email: 'E-posta',
    phone: 'Telefon',
    currentPassword: 'Mevcut Şifre',
    newPassword: 'Yeni Şifre (En az 6 karakter)',
    confirmPassword: 'Yeni Şifre (Tekrar)',
    changePasswordButton: 'Şifre Değiştir',
    unassigned: 'Atanmamış',
    unknown: 'Bilinmiyor'
  },
  userCompanyInfo: {
    loading: 'Şirket bilgileri yükleniyor...',
    error: 'Şirket bilgileri yüklenirken bir hata oluştu.',
    retry: 'Tekrar Dene',
    companyInfo: 'Şirket Bilgileri',
    departmentInfo: 'Departman Bilgileri',
    noCompanyTitle: 'Şirket Bilgisi Bulunamadı',
    noCompanyText: 'Henüz bir şirkete bağlı değilsiniz. Şirket ataması için yöneticinizle iletişime geçin.',
    noDepartmentTitle: 'Departman Bilgisi Bulunamadı',
    noDepartmentText: 'Henüz bir departmana atanmadınız. Departman ataması için yöneticinizle iletişime geçin.',
    active: 'Aktif',
    departmentName: 'Departman Adı',
    userRole: 'Kullanıcı Rolü',
    joinDate: 'Katılım Tarihi',
    notSpecified: 'Belirtilmemiş',
    companyName: 'Şirket Adı',
    companyCode: 'Şirket Kodu',
    companyAddress: 'Şirket Adresi',
    companyPhone: 'Şirket Telefonu',
    companyEmail: 'Şirket E-postası',
    companyWebsite: 'Şirket Web Sitesi',
    establishedDate: 'Kuruluş Tarihi',
    employeeCount: 'Çalışan Sayısı'
  },
  managerDashboard: {
    loading: 'Panel yükleniyor...',
    welcome: 'Hoş Geldiniz!',
    departmentStats: 'Departman İstatistikleri',
    totalEmployees: 'Toplam Çalışan',
    managedDepartments: 'Yönetilen Departmanlar',
    quickActions: 'Hızlı İşlemler',
    departmentEmployees: 'Departman Çalışanları',
    profileSettings: 'Profil Ayarları',
    department: 'Departman'
  },
  managerProfile: {
    loading: 'Profil yükleniyor...',
    title: 'Profil Bilgileri',
    generalInfo: 'Genel Bilgiler',
    personalInfo: 'Kişisel Bilgiler',
    changePassword: 'Şifre Değiştir',
    department: 'Departman',
    role: 'Rol',
    name: 'Ad',
    surname: 'Soyad',
    email: 'E-posta',
    currentPassword: 'Mevcut Şifre',
    newPassword: 'Yeni Şifre',
    confirmPassword: 'Yeni Şifre (Tekrar)',
    changePasswordButton: 'Şifre Değiştir',
    passwordMismatch: 'Yeni şifreler eşleşmiyor',
    passwordChangeSuccess: 'Şifre başarıyla güncellendi',
    passwordChangeError: 'Şifre değiştirme başarısız',
    profileLoadError: 'Profil bilgileri alınamadı'
  },
  managerUserList: {
    loading: 'Kullanıcılar yükleniyor...',
    department: 'Departman',
    role: 'Rol',
    deleteUser: 'Kullanıcı Silme',
    deleteConfirmation: 'kullanıcısını silmek istediğinize emin misiniz?',
    cancel: 'İptal',
    delete: 'Sil',
    deleteSuccess: 'Kullanıcı başarıyla silindi.',
    deleteError: 'Kullanıcı silinirken bir hata oluştu.',
    emptyList: 'Bu departmanda henüz kullanıcı bulunmuyor.',
    usersLoadError: 'Kullanıcılar getirilemedi'
  },
  common: {
    loading: 'Yükleniyor...',
    error: 'Hata',
    success: 'Başarılı',
    cancel: 'İptal',
    save: 'Kaydet',
    delete: 'Sil',
    edit: 'Düzenle',
    add: 'Ekle',
    search: 'Ara',
    filter: 'Filtrele',
    refresh: 'Yenile',
    back: 'Geri',
    next: 'İleri',
    previous: 'Önceki',
    close: 'Kapat',
    confirm: 'Onayla',
    yes: 'Evet',
    no: 'Hayır',
    logout: 'Çıkış',
  },
  adminDashboard: {
    loading: 'Dashboard yükleniyor...',
    welcome: 'Hoş Geldin!',
    systemStats: 'Sistem İstatistikleri',
    totalUsers: 'Toplam Kullanıcı',
    totalCompanies: 'Toplam Şirket',
    totalDepartments: 'Toplam Departman',
    activeUsers: 'Aktif Kullanıcı',
    pendingUsers: 'Bekleyen Kullanıcı',
    dataLoadError: 'Dashboard verileri yüklenirken bir hata oluştu'
  },
  adminUserList: {
    loading: 'Yükleniyor...',
    addNewUser: 'Yeni Kullanıcı Ekle',
    edit: 'Düzenle',
    delete: 'Sil',
    deleteUser: 'Kullanıcıyı Sil',
    deleteConfirmation: 'Bu kullanıcıyı silmek istediğinizden emin misiniz?',
    cancel: 'İptal',
    deleteSuccess: 'Kullanıcı silindi',
    deleteError: 'Kullanıcı silinemedi',
    usersLoadError: 'Kullanıcılar alınamadı'
  },
  adminUserForm: {
    loading: 'Yükleniyor...',
    name: 'Ad',
    surname: 'Soyad',
    email: 'E-posta',
    department: 'Departman',
    role: 'Rol',
    selectDepartment: 'Departman Seçin',
    save: 'Kaydet',
    warning: 'Uyarı',
    selectDepartmentWarning: 'Lütfen bir departman seçiniz.',
    saveSuccess: 'Kullanıcı kaydedildi',
    saveError: 'Kullanıcı kaydedilemedi',
    userLoadError: 'Kullanıcı bilgisi alınamadı',
    departmentsLoadError: 'Departmanlar alınamadı'
  },
};