import { Translations } from './types';

export const tr: Translations = {
  auth: {
    login: {
      title: 'Giriş Yap',
      email: 'E-Posta',
      password: 'Şifre',
      loginButton: 'Giriş',
      forgotPassword: 'Şifremi unuttum,',
      resetPassword: 'Şifre sıfırla',
      activateAccount: 'Hesabını aktive etmek için,',
      activate: 'Aktive et',
      loginError: 'Giriş başarısız',
      checkCredentials: 'Lütfen bilgilerinizi kontrol edin.',
      authError: 'Yetki Hatası',
      roleNotDefined: 'Yetkiniz tanımlı değil.',
    },
    forgotPassword: {
      title: 'Şifre Sıfırlama',
      email: 'E-Posta',
      emailPlaceholder: 'E-posta adresinizi girin',
      sendButton: 'Sıfırlama Bağlantısı Gönder',
      sendResetLink: 'Sıfırlama Bağlantısı Gönder',
      backToLogin: 'Giriş Sayfasına Dön',
      resetLinkSent: 'Sıfırlama Bağlantısı Gönderildi',
      checkEmail: 'E-posta adresinizi kontrol edin.',
      error: 'Hata',
      tryAgain: 'Lütfen tekrar deneyin.',
    },
    activation: {
      title: 'Hesap Aktivasyonu',
      emailPlaceholder: 'E-posta adresinizi girin',
      sendButton: 'Aktivasyon E-postası Gönder',
      orText: 'veya',
      tokenPlaceholder: 'Aktivasyon kodunu girin',
      activationCode: 'Aktivasyon Kodu',
      activateButton: 'Aktive Et',
      backToLogin: 'Giriş Sayfasına Dön',
      activationSuccess: 'Aktivasyon Başarılı',
      accountActivated: 'Hesabınız başarıyla aktive edildi.',
      activationError: 'Aktivasyon Hatası',
      invalidCode: 'Geçersiz aktivasyon kodu.',
    },
  },
  common: {
    loading: 'Yükleniyor...',
    error: 'Hata',
    success: 'Başarılı',
    cancel: 'İptal',
    save: 'Kaydet',
    delete: 'Sil',
    edit: 'Düzenle',
    add: 'Ekle',
    search: 'Ara',
    filter: 'Filtrele',
    refresh: 'Yenile',
    back: 'Geri',
    next: 'İleri',
    previous: 'Önceki',
    close: 'Kapat',
    confirm: 'Onayla',
    yes: 'Evet',
    no: 'Hayır',
  },
};